version: '3.8'
services:
  postgres:
    image: postgres:13.1
    ports:
      - '5832:5432'
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'test']
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis:6.0.9
    ports:
      - '6893:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=sqs
      - EDGE_PORT=4566
    healthcheck:
      test: ['CMD', 'awslocal', 'sqs', 'list-queues']
      interval: 5s
      timeout: 10s
      retries: 5
  init-localstack:
    image: localstack/localstack
    entrypoint: /bin/bash
    command: -c "awslocal sqs create-queue --queue-name caliobase-shared-queue-dead-letter-queue && awslocal sqs create-queue --queue-name caliobase-shared-queue"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      localstack:
        condition: service_healthy
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: testtest
      MINIO_ROOT_PASSWORD: testtest
      MINIO_DOMAIN: s3.localhost.localstack.cloud
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - minio:/data
  init-minio:
    image: minio/mc
    entrypoint: /bin/sh
    command: -c "mc alias set local http://minio:9000 testtest testtest && mc mb local/caliobase"
    depends_on:
      minio:
        condition: service_healthy
  init-postgres:
    image: postgres:13.1
    entrypoint: /bin/bash
    command: -c "createdb -h postgres -U test caliobase && createdb -h postgres -U test typeorm-migrations"
    environment:
      PGPASSWORD: test
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  minio:
  postgres:
  redis:
